### ISSUE TITLE
Python Tutor doesn't resize too well

### ISSUE THREAD

**Issue by DavidLeoni** [DavidLeoni/jupman#93]
I made an attempt at fluid fonts in #92 but got stuck with several issues, among them Python Tutor needs more work for resizing the pesky green/red arrow svg. I post here what I've got so far.

```css

.pytutorVisualizer  .ui-resizable{
    min-width: 100% !important;
    font-size:1rem;
}

div.ExecutionVisualizer .typeLabel {
    font-size:1rem !important;    
}
div.ExecutionVisualizer #heapHeader {
    font-size:1rem !important;    
}

div.ExecutionVisualizer .stackFrameHeader{
    font-size:1rem !important;  
}

div.ExecutionVisualizer #stackHeader{
    font-size:1rem !important;  
}

.vizLayoutTd  table {
    font-size:1rem !important;
}
```
